### ISSUE TITLE
Binder link opens on missing page

### ISSUE THREAD

**Issue by mattjbr123** [cedadev/padocc#41]
Minor issue:
The 'Example Notebooks here' link in the README loads https://hub.binder.curvenote.dev/user/cedadev-kerchunk-builder-fpgzxms2/tree/showcase/notebooks by default, which 404s. 
The link in the README goes to mybinder.org/v2/gh/cedadev/ **kerchunk-builder** .git/main?filepath=showcase/notebooks
which AFAICT is the old repo that used to host this project, which doesn't have any files in it anymore. I guess binder is not clever enough to pick up the redirect to this new repo. 
Should be pretty easy to fix, I'll attempt to draft a PR.

**Comment by mattjbr123** [comment]
Just changing the link to
mybinder.org/v2/gh/cedadev/ **padocc** .git/main?filepath=showcase/notebooks 
seems to do the job

**Comment by mattjbr123** [comment]
PR: #42

**Comment by dwest77a** [comment]
Added this fix to the branch MigrationOO which should be merged with the next release very shortly!
